language: node_js
node_js:
- '8'
script: npm run test
cache:
  directories:
  - node_modules
before_deploy: npm run semantic-release pre
after_deploy: npm run semantic-release post
deploy:
  skip_cleanup: true
  provider: script
  script: npm publish
  on:
    repo: musicociel/nodejs-android-binaries
    branch: master
env:
  global:
  - secure: e0HBzqlwvzSqVzSjobaCoshwmoXhJRisut/srVJCEn/QVB1uyW66YsXnsNaAWFbExFdiSfoB8Yvo4sAN9No5/OxKcin1r2gURaYxfdnVGQ8XMfC2DukBfWMV0cfNLFhDCnI7WGlMNe1pBLhpF1C0tnCER8t6VfVBo+6R/mTuwCcp0VzZyTyDjK0cTQIjoRYKpckkPAWHfyVKWOoYsDoH2jcnN/pUPcTnnWh9qnmi4JRkP0ErwnoGQvEraJNjBJFTd/U34TBIWOu6MRWlNHA7yZjdYFVPm66Np2L7hlomO6V74k9BfpBa958KFerD+Y4axIxBcXeyHbWGCSI630maN7gnE/lwWR+c3FqbXiA6ZS7Y8G9tbLHdp00k21pf1EqUjxjQB/HmFOVI1/vpz8buWDbSKtfHL1YhnzMHajmsm2Uvblnh3ALuBDTE7vtq20w/9A49R0vV15LaQplW47Hb1RIWG7dL0+J91/loikNFzES+iNrB02TQ/E2K64UfiKR7rEVALILB3d8gv6K/bgIwpAE8f1yzQOCOPb4nXwd2nP3CgFYxtF5CZ0wzyDwjahS5amA1lLlfI9qMFNcozMCLp/Cn8kf/7S2gZhqRkv/AknPWvbblqCILQUGcrsFbb0QHHq8rQ3IsNkkzNP6i5dg7R7gi0mFHDvRLSsHxC2mvrwk=
  - secure: qWWPZFtwMtRr8ScXH0l8UNbr1xMf7jkkWEwcmLnZJcLTdZ6hPEP40iTt+ShsQES2tUj2dWg23xTAX2R0AE61Bal422ZXC3/4YLx5+2s1Jw86FCmlEWCQ5d2tqAcdiKcluhpF5pCMCDTRU7eLUgCCSo2d/Nx89PttFaFFR44LYkmwesnCH9YUxf3DJ1DahHpzyMyG10FMpYkXsEblk/dJ2l98zsske1hXPC//fXAXytLc4H6w6Ek9utTJlpbRJ959tpGYDKoN7qEoR0FM1mP1PGWYqVvpZ77oO9KQlEinqeoyKkiT7/g4egGETGW9AmKVm2QTIHVrV2ZE/v5bYJ0w0sa/77hox4LnXc1jUM/lhghgiMBBF+ACr4uTeBt3MWzlULrWSOhkGeWMt6s44JzCp0s9/W9ep5k4dhtSQOlxV4IgBxOYTALemBwmgol+E3UDVjvBhY1zGcCiK04uJ8BofQoECqX4S00M/fFmmkQ4mxF9C2z9/sv28jSHk3six1Zw8LY7PUmxzAMiy3sfeF2w4DUwKqeIQl/w8L3xyORqXYVmvRk+juvgcUHsDNcIPXPVdkms97L9I0dHkGtE6XnGxyR2L5OAXPPtXR4+Qz0jIyn8rmxEQuNmiK1TW92cfcM7c/HVt1iBpDQnN1kpVuCQVVieGzOfhCLSIf8cEIwJH5E=
